config/routes.rb
Rails.application.routes.draw do

  root to: 'docs#index'

  get '/login' => 'sessions#new'
  get '/auth/github/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  post '/docs/:id/like', to: 'likes#like', as: 'like'
  delete '/docs/:id/dislike', to: 'likes#dislike', as: 'dislike'

  resources :docs

end

app/models/doc.rb
class Doc < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, use: :slugged

  has_many :related_links
  belongs_to :user
  has_many :likes
  has_many :users, through: :likes

  accepts_nested_attributes_for :related_links, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :title, :description, :implementation

  validates :title, length: { minimum: 5 }

  acts_as_ordered_taggable

  def has_been_liked_by_this_user(user)
    likes.where(user_id: user).exists?
  end

  def last_likes(x = 4)
    users.last(x).reverse
  end

  def other_likes(x=4)
    likes.count - last_likes(10).count
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :doc
end

app/models/related_link.rb
class RelatedLink < ActiveRecord::Base
  belongs_to :doc

  validates_presence_of :link, :title
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :docs
  has_many :likes

  has_many :docs_liked, through: :likes, source: :docs

  def self.create_from_omniauth(auth_hash)
    self.create(provider: auth_hash[:provider],
                uid: auth_hash[:uid],
                name: auth_hash[:info][:name],
                email: auth_hash[:info][:email],
                avatar: auth_hash[:info][:image],
                token: auth_hash[:credentials][:token],
                nickname: auth_hash[:info][:nickname]
               )
  end

  def liked?(doc)
    likes.where(doc_id: doc).exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def logged_in?
    !!current_user #double negation to convert to boolean
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] #memoized
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy]

  def index
    @q = Doc.ransack(params[:q])
    @docs = @q.result(distinct: true).order(updated_at: :desc)

    if params[:author]
      @docs = @docs.where(user_id: params[:author])
      @author = User.find params[:author]
    end

    if params[:tag]
      @docs = @docs.tagged_with(ActsAsTaggableOn::Tag.find(params[:tag]))
    end

    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
  end

  def new
    @doc = Doc.new
  end

  def edit
  end

  def create
    @doc = Doc.new(doc_params)

    @doc.user = current_user if current_user

    respond_to do |format|
      if verify_recaptcha(model: @doc) && @doc.save
        respond_with_success(format, t('doc_created_success'))
      else
        respond_with_unprocessable_entity(format, :new)
      end
    end
  end

  def update
    respond_to do |format|
      if @doc.update(doc_params)
        respond_with_success(format, t('doc_updated_success'))
      else
        respond_with_unprocessable_entity(format, :edit)
      end
    end
  end

  def destroy
    @doc.destroy
    respond_to do |format|
      format.html { redirect_to docs_url, notice: t('doc_deleted_success') }
      format.json { head :no_content }
    end
  end

  private

    def respond_with_success(format, message)
      format.html { redirect_to @doc, notice: message}
      format.json { render :show, status: :created, location: @doc }
    end

    def respond_with_unprocessable_entity(format, view)
      format.html { render view }
      format.json { render json: @doc.errors, status: :unprocessable_entity }
    end

    def set_doc
      @doc = Doc.friendly.find(params[:id])
    end

    def doc_params
      params[:doc].permit(:title, :description, :implementation, :tag_list, related_links_attributes: [:id, :link, :title, :_destroy])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def like
    doc = Doc.friendly.find(params[:doc])
    Like.create(user: current_user, doc: doc )

    redirect_to doc_path(doc), notice: t('thanks for the like')
  end

  def dislike
    doc = Doc.friendly.find(params[:doc])
    Like.where(user: current_user, doc: doc).destroy_all

    redirect_to doc_path(doc), notice: t('like removed')
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/github'
  end

  def create
    @user = User.find_by_provider_and_uid(auth_hash[:provider], auth_hash[:uid]) || User.create_from_omniauth(auth_hash)
    if @user
         session[:user_id] = @user.id
    end

    redirect_to root_url
  end

  def destroy
    reset_session
    redirect_to root_url
  end

  protected
  def auth_hash
    request.env['omniauth.auth']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      language ||= :plaintext
      CodeRay.scan(code, language).div(:line_numbers => :table)
    end
  end

  def markdown(text)
    @coderayified ||= CodeRayify.new(:filter_html => true,
                               :hard_wrap => true)

    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :strikethrough => true,
      :lax_html_blocks => true,
      :superscript => true
    }

    @markdown_to_html = Redcarpet::Markdown.new(@coderayified, options)
    @markdown_to_html.render(text).html_safe
  end
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/docs/_doc.html.erb
<div class="doc-panel">
  <div class="panel-body">

    <div class="row">
      <div class="col-md-8">
        <h2><%= link_to doc.title, doc%></h2>
      </div>
      <div class="col-md-4">
        <div class="date-and-user-info">
          <div class="small faded">
            <%= t('updated at') + " " + l(doc.updated_at, format: :short) %>
          </div>
          <% if doc.user %>
            <%= link_to docs_path(author: doc.user) do %>
              <%= image_tag doc.user.avatar, class: "doc-preview-user-avatar", alt: "user-avatar" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <p>
      <%= doc.description%>
    </p>

    <div class="row">
      <div class="col-md-9">
        <% doc.tags.each do |t| %>
          <%= link_to docs_path(tag: t.id) do %>
            <div class="small-tag">
              <%= t %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="col-md-3">
        <div class=" pull-right">

          <% if doc.users.present? %>
            <%= icon('heart') %> by
            <% doc.last_likes.each do |user| %>
              <%= image_tag user.avatar, class: "small-liked-avatar" %>
            <% end %>

            <% if doc.other_likes > 0 %>
              and <%= doc.other_likes %> others
            <% end %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/docs/_doc_search_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 text-center">
    <%= search_form_for @q do |f| %>

      <div class="form-group form-inline">
        <%= f.search_field :title_or_description_or_implementation_or_related_links_title_cont, placeholder: t(:doc_search), class: "form-control" %>

        <%= f.submit nil, class: 'btn btn-default' %>
      </div>

    <% end %>
  </div>
</div>

app/views/docs/_form.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'editor' %>
<% end %>

<%= form_for(@doc) do |f| %>

  <div class="form-group">

    <% if @doc.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

        <ul>
        <% @doc.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <br>

    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %><br>

    <br>

    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control description_area" %><br>

    <br>

    <div class="row">
      <div class="col-md-7">
        <%= f.label :implementation %><br>
        <%= f.text_area :implementation, class: "implementation_area" %><br>
        <div class="ace-container">
          <div id="editor">
          </div>
        </div>
      </div>
      <div class="col-md-5">
        <h3>Tips:</h3>
        <ul>
          <li> <%= t('support markdown') %> <a href="https://help.github.com/articles/github-flavored-markdown/">GitHub Flavored Markdown</a></li>
          <li> <%= t('login for private repo code') %> </li>
          <li> <%= t('types of imported links')  %>:</li>
          <ul>
            <li>
              <%= t('a file')  %>:
              <a>https://github.com/coopera/that-s-the-way-you-do-it/blob/master/app/models/doc.rb</a>
            </li>
            <li>
               <%= t('a line from a file') %>:
               <a>https://github.com/coopera/that-s-the-way-you-do-it/blob/master/app/models/doc.rb#L1</a>
            </li>
            <li>
              <%= t('a line interval from a file') %>:
              <a>https://github.com/coopera/that-s-the-way-you-do-it/blob/master/app/models/doc.rb#L5-L7</a>
            </li>
            <li>
            <li>
              <%= t('a commit') %>:
              <a>https://github.com/coopera/that-s-the-way-you-do-it/commit/d7f365db9777b4cb6e1c5799a2e431c58aaf3a19</a>
             </li>
            <li>
              <%= t('a pull request') %>:
              <a>https://github.com/coopera/that-s-the-way-you-do-it/pull/7</a>
             </li>
          </ul>
        </ul>
        <li> <%=t('free to edit') %> </li>
      </div>
    </div>

    <br>

    <%= f.label :related_links %><br>
    <div id="related_links">
      <%= f.fields_for :related_links do |related_link| %>
        <%= render 'related_link_fields', f: related_link %>
      <% end %>

      <div class="links">
        <%= link_to_add_association t(:add_link), f, :related_links %>
      </div>
    </div>

    <br>

    <%= f.label :tags %><br>
    <%= f.text_field :tag_list, value: @doc.tag_list.to_s, class: "tag_list form-control"%>

    <br>

    <%= recaptcha_tags %>

    <br>

    <div class="actions">
      <%= f.submit t('submit doc'), class: "btn btn-primary"%>
    </div>

  </div>
<% end %>

<script>
  <% if logged_in? %>
    token = "<%= current_user.token %>"
  <% else %>
    token = undefined
  <% end %>
</script>

app/views/docs/_related_link_fields.html.erb
<div class="nested-fields">
  <div class="field f_25">
    <%= f.label :title %>
    <%= f.text_field :title, class: "fill_witdh form-control" %>
  </div>
  <div class="field f_25">
    <%= f.label :link %>
    <%= f.text_field :link, class: "fill_witdh form-control"%>
  </div>
  <%= link_to_remove_association t(:remove_link), f %>

  <br>
  <br>
</div>

app/views/docs/_tag.html.erb
<%= link_to docs_path(tag: tag.id) do %>
  <div class="small-tag">
    <%= tag %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>
  <%= t('edit doc title') %>
</h1>

<%= render('utils/menu') %>

<%= render 'form' %>

app/views/docs/index.html.erb
<p id="notice"><%= notice %></p>

<%= render "doc_search_form" %>

<% if @author %>
  <p>
    <%= t('docs written by') %>: <strong><%= @author.name %></strong>
  </p>
<% end %>

<% unless @docs.empty? %>
  <%= render @docs %>
  <p>
    <%= @docs.count %> document(s) match the current search.
  </p>
<% else %>
  <%= t('no docs')%>
<% end %>

<%= render "shared/tag_list" %>

app/views/docs/new.html.erb
<h1>
  <%= t('new doc title') %>
</h1>

<%= link_to t('cancel'), docs_path, class: "pull-right" %>

<br>

<p>
  <strong>
    <%= t('note twydi creator') %>
  </strong>
</p>

<%= render 'form' %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="doc">
  <div class="row">
    <div class="col-md-11">
      <h1> <%= @doc.title %> </h1>
    </div>
    <div class="col-md-1">
      <% if @doc.user %>
        <%= link_to docs_path(author: @doc.user) do %>
          <%= image_tag @doc.user.avatar, class: 'doc-show-avatar' %>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if current_user == @doc.user %>
    <div class="action-row">
      <%= link_to icon("edit") + " " + t('edit doc'), edit_doc_path(@doc), class: "btn btn-default" %>
      <%= link_to icon("trash-o") + " " + t('delete doc'), @doc, method: :delete, class: "btn btn-default", data: {confirm: "Are you sure?"} %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">

      <% if @doc.users.present? %>
        <%= icon('heart') %> by
        <% @doc.last_likes(10).each do |user| %>
          <%= image_tag user.avatar, class: "liked-avatar" %>
        <% end %>

        <% if @doc.other_likes(10) > 0 %>
          and <%= @doc.other_likes %> others
        <% end %>
      <% else %>
        <div class="no-likes">
          <%= t('no likes yet') %>
        </div>
      <% end %>

    </div>

    <div class="col-md-6 doc-created-and-updated">
      <%= t('created at') + " " + l(@doc.created_at, format: :short) %>
      ,
      <%= t('updated at') + " " + l(@doc.updated_at, format: :short) %>
    </div>
  </div>

  <p>
    <%= @doc.description %>
  </p>

  <strong>Tags</strong>
  <p>
    <% if @doc.tags.present? %>
      <%= render partial: "docs/tag", collection: @doc.tags  %>
    <% else %>
      <%= t('no_tags') %>
    <% end %>
  </p>

  <hr>

  <p>
    <%= markdown @doc.implementation %>
  </p>

  <hr>

  <strong>Useful Links</strong>
  <p>
    <% if @doc.related_links.present? %>
      <% @doc.related_links.each do |link| %>
        <li>
          <%= link_to link.title, link.link %>
        </li>
      <% end %>
    <% else %>
     <%= t('no_links') %>
    <% end %>
  </p>

  <h3><%= t('feedback') %></h3>

  <% if logged_in? %>

    <% if current_user.liked?(@doc) %>
      <button type="button" name="like-button" class="btn-like disabled">
        <%= t('already liked') %> <i class="fa fa-heart"></i>
      </button>
      <%= t('doesnt like it anymore') %>
      <%= link_to t('remove like'), dislike_path(doc: @doc), method: :delete%>
    <% else %>

      <div class="like-container">
        <%= link_to like_path(doc: @doc), method: :post do %>
          <button type="button" name="like-button" class="btn-like">
            <%=  t('this was useful') %> <i class="fa fa-heart"></i>
          </button>
        <% end %>
      </div>

    <% end %>

  <% else %>

    <button type="button" name="like-button" class="btn-like disabled">
      <%=  t('this was useful') %> <i class="fa fa-heart"></i>
    </button>

    <%= link_to t('login for feedback'), login_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>That's The Way you Do It</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

  <%= favicon_link_tag 'twydi_favicon.png' %>
  <%= favicon_link_tag 'twydi_favicon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">

    <div class="row">

      <div class="col-md-5 up-menu">
        <%= render "utils/menu" %>
      </div>

      <div class="col-md-2">
        <%= link_to root_url do %>
          <%= image_tag "logo.png", class: "img-responsive logo", alt: "logo" %>
         <% end %>
         <p class="text-center">
           "WTF is a Twydi?" Read <a href="https://github.com/IgorMarques/that-s-the-way-you-do-it/blob/master/README.md">here ;)</a>
         </p>
      </div>

      <div class="col-md-5 up-menu">
        <div class="pull-right">
          <% if logged_in? %>
            <%= current_user.name %>
            <%= link_to 'Log Out', logout_path %>
          <% else %>
            <%= link_to 'Log In with Github', login_path %>
          <% end %>
        </div>
      </div>

    </div>

    <%= yield %>

    <hr>

    <div class="footer">
      <strong>Found a bug or has some feedback? </strong><br>

      Please send me an e-mail at: igormarquessilva @ gmail.com <br>

      Or create an issue at the repo: <br>

      <a href="https://github.com/coopera/that-s-the-way-you-do-it">https://github.com/coopera/that-s-the-way-you-do-it</a><br>

      Thanks for testing the app :)

      <hr>

      <%= DateTime.now.year %> © <a href="http://igormarques.github.io">Igor Marques da Silva</a> & <a href="http://coopera.github.io">Coopera Lab</a>

  </div>

</body>
</html>

app/views/shared/_tag.html.erb
<%= link_to docs_path(tag: tag.id) do %>
  <div class="small-tag tag-count">
      <%= tag.name %> | <%= tag.taggings_count %>
  </div>
<% end %>

app/views/shared/_tag_list.html.erb
<h3>list of tags</h3>

<%= render partial: "shared/tag", collection: @tags %>

app/views/utils/_menu.html.erb
<ul class="menu">
  <li>
    <%= link_to t('all_docs'), docs_path %>
  </li>
  <li>
    <% if logged_in? %>
      <%= link_to t('your_docs'), docs_path(author: current_user) %>
    <% end %>
  </li>
  <li class="btn btn-primary btn-xs">
    <%= link_to t('new doc'), new_doc_path %>
  </li>
</ul>